### ISSUE TITLE
3D卡片轮播取值有问题

### ISSUE THREAD

**Issue by taojeff** [BlackStarLang/BSFramework#5]
设置`        _looperView.autoLoop = NO;
        _looperView.loopStyle = BSLOOP_STYLE_NORMAL;`这两个属性后3D轮播为非自动滚动，此时手动滚动一个循环后，会出现图片数据不一致，有逆向回滚的现象

**Comment by BlackStarLang** [comment]
我这里使用模拟器试了下，暂时没发现问题，能提供具体的代码片段吗？
我的demo代码如下
        _looperView = [[BSLooperView alloc]initWithFrame:CGRectMake(20, 300, self.view.width - 40, 180)];
        _looperView.cellName = @"BSCollectionViewCell";
        _looperView.delegate = self;
        _looperView.itemSize = CGSizeMake(self.view.width - 120 ,180);
        _looperView.scale = 0.8;
        _looperView.isInfinite = YES;
        _looperView.autoLoop = NO;
        _looperView.duration = 2;
        _looperView.loopStyle = BSLOOP_STYLE_NORMAL;
        ///========================
        /// 3D 轮播样式属性
        ///========================
        // 卡片样式，minimumLineSpacing 无效
        _looperView.minimumLineSpacing = 15;
        
        // 卡片样式，centerOffset 无效
        _looperView.centerOffset = 0;
        
        // 卡片样式无效
        _looperView.scrollDirection = UICollectionViewScrollDirectionHorizontal;
